import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MyContext, MyProvider } from "./MyContext";
import AppBar from "./pages/appBar/AppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MyProvider>
        <body className={inter.className}>
          <AppBar />
          <div>root layout</div>
          <div id="root">
            {children}
          </div>
        </body>
      </MyProvider>
    </html>
  );
}
